apiVersion: v1
kind: Service
metadata:
  name: <nome do serviço>-service
  namespace: <nome do projeto>-service #Aqui acho interessante usar o -service para diferenciar do namespace do frontend
spec:
  type: ClusterIP
  selector:
    app: <nome do serviço>-service
  ports:
    - name: "<>-port"
      port: 80
      targetPort: 80
      protocol: TCP